name: Germany Job Tracker

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  scrape-and-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas python-telegram-bot openpyxl

      - name: Run scraper
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          mkdir -p results
          python job_scraper.py
          mv jobs_*.xlsx results/

      - name: Commit Excel file to repo
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add results/*.xlsx
          git commit -m "🗂️ Add new job results"
          git push
        continue-on-error: true
